# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build the OIDC Mockery binary
    cmds:
      - go build -o bin/oidc-mockery .

  run:
    desc: Run the OIDC Mockery server
    cmds:
      - bin/oidc-mockery
  
  stop:
    desc: Stop the OIDC Mockery server
    cmds:
      - pkill oidc-mockery || true

  test:
    desc: Run functional tests with k6
    cmds:
      - k6 run test/full-flow.k6

  test-1:
    desc: Run 1 iteration of functional test with k6
    cmds:
      - k6 run test/full-flow.k6 --vus 1 --duration 1s

  tidy:
    desc: Clean up Go module dependencies
    cmds:
      - go mod tidy

  update:
    desc: Update Go module dependencies
    cmds:
      - go get -u -v .

  image-build:
    desc: Build Docker image
    cmds:
      - podman build --cgroup-manager=cgroupfs -t oidc-mockery:local .

  image-run:
    desc: Run Docker container
    cmds:
      - podman run --cgroup-manager=cgroupfs --rm -p 8080:8080 -v {{.PWD}}/config.yaml:/config.yaml:ro oidc-mockery:local